name: Legacy version maintenance

<<<<<<< HEAD
=======

>>>>>>> 455e528eddb148d03828ce14865afd835f8071a6
# label trigger
on:
  label:
    types: [created]

<<<<<<< HEAD
=======


>>>>>>> 455e528eddb148d03828ce14865afd835f8071a6
jobs:
  maintenance:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.label.name, 'branch:release-branch.')
    steps:
      - name: Checkout to website
        uses: actions/checkout@v4
        with:
          ref: website
          path: .website
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          path: .main
      # actions/checkout cannot fetch tags even though using fetch-tags
      # see issue: https://github.com/actions/checkout/issues/1471
      - name: Fetch all tags
        working-directory: .main
        run: |
          git fetch --all --tags --prune

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Skip Cache Parser Tool
        run: |
<<<<<<< HEAD
          go env -w GOPRIVATE=github.com/luoliwoshang/llpkgstore
      - name: Set up Parser Tool
        run: |
          go install -v github.com/luoliwoshang/llpkgstore/cmd/maintain@latest
=======
          go env -w GOPRIVATE=github.com/MeteorsLiu/llpkgstore
      - name: Set up Parser Tool
        run: |
          go install -v github.com/MeteorsLiu/llpkgstore/cmd/maintain@gha-test
>>>>>>> 455e528eddb148d03828ce14865afd835f8071a6
      - name: Copy llpkgstore.json to root
        continue-on-error: true
        run: |
          # ignore error
          ls .website .website/public
          cp .website/public/llpkgstore.json .main
          rm -rf .website
      - name: Run maintenance process
        working-directory: .main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
<<<<<<< HEAD
          maintain labelcreate -l "${{ github.event.label.name }}"
=======
          maintain labelcreate -l "${{ github.event.label.name }}"
>>>>>>> 455e528eddb148d03828ce14865afd835f8071a6
