name: Post-processing


# don't limit to main branch
# consider maintenance branch
on:
  push:
    branches:
      - 'release-branch.**'
      - main


jobs:
  post-processing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          path: .main

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Skip Cache Parser Tool
        run: |
          go env -w GOPRIVATE=github.com/MeteorsLiu/llpkgstore
      - name: Set up Parser Tool
        run: |
          go install -v github.com/MeteorsLiu/llpkgstore/cmd/llpkgstore@gha-test
      - name: Checkout to website
        uses: actions/checkout@v4
        with:
          ref: website
          path: .website

      - name: Copy llpkgstore.json to root
        continue-on-error: true
        run: |
          # ignore error
          ls .website .website/public
          cp .website/public/llpkgstore.json .main
          rm -rf .website

      - name: Run post-processing process
        working-directory: .main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          llpkgstore postprocessing

      - name: Checkout website branch
        uses: actions/checkout@v4
        with:
            ref: website
            path: .website

      - name: Move llpkgstore.json to website
        run: |
            mv .main/llpkgstore.json .website/public

      - name: Commit and push changes
        working-directory: .website
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add public/llpkgstore.json
            git commit -m "Update llpkgstore.json"
            git push
  release-binary-files:
    strategy:
      matrix:
        os:
          # amd64 darwin
          - macos-13
          # arm64 darwin
          - macos-latest
          # amd64 linux
          - ubuntu-24.04
          # ard64 linux
          - ubuntu-24.04-arm
        llvm: [18]
    runs-on: ${{matrix.os}}
    needs: [post-processing]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Skip Cache Parser Tool
        run: |
          go env -w GOPRIVATE=github.com/MeteorsLiu/llpkgstore
      - name: Set up Parser Tool
        run: |
          go install -v github.com/MeteorsLiu/llpkgstore/cmd/llpkgstore@gha-test
      - name: Install dependencies
        if: startsWith(matrix.os, 'macos')
        run: |
          brew update
          brew install cmake conan cjson

      - name: Install dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake python3 python3-pip pkg-config
          python3 -m pip install conan
      - name: Set up Conan
        run: |
          conan profile detect
      - name: Run release process
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          llpkgstore release
  rebuild-github-pages:
    runs-on: ubuntu-latest
    needs: [release-binary-files]
    permissions:
      pages: write
      id-token: write
    strategy:
        matrix:
            node-version: [23.8.0]
    steps:
      - name: Checkout to website
        uses: actions/checkout@v4
        with:
          ref: website
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - name: Install Dependencies
        uses: borales/actions-yarn@v4
        with:
            cmd: install
      - name: Build
        uses: borales/actions-yarn@v4
        with:
            cmd: build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
            path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4